[project]
name = "comp121"
version = "0.1.0"
description = "Course notes for COMP121 at Krea University"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "metapensiero-sphinx-d2>=0.10",
    "sphinx-design>=0.6.1",
    "sphinx-tabs>=3.4.7",
    "sphinx-toolbox>=4.2.0",
    "sphinx>=9.0.0",
    "sphinxcontrib-d2lang>=0.0.2",
]
